# Generated by Django 2.0.4 on 2018-04-09 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseICD10Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('certainty', models.CharField(default='G', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ICD10',
            fields=[
                ('primary_key_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('star_key_number', models.CharField(blank=True, max_length=10, null=True)),
                ('additional_key_number', models.CharField(blank=True, max_length=10, null=True)),
                ('preferred_short_description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='KeyDateCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('diagnose_all_icd_10', models.ManyToManyField(related_name='icd10s', related_query_name='icd10s', through='keydatecases.CaseICD10Connection', to='keydatecases.ICD10')),
            ],
        ),
        migrations.AddField(
            model_name='caseicd10connection',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', related_query_name='key_date_cases', to='keydatecases.KeyDateCase'),
        ),
        migrations.AddField(
            model_name='caseicd10connection',
            name='icd_10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', related_query_name='icd_10s', to='keydatecases.ICD10'),
        ),
    ]
